version: '3'

services:
  app-dev:
    image: your-image:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8000:8080"
  app-systest:
    image: your-image:latest
    environment:
      - SPRING_PROFILES_ACTIVE=systest
    ports:
      - "8082:8080"
  app-uat:
    image: your-image:latest
    environment:
      - SPRING_PROFILES_ACTIVE=uat
    ports:
      - "8083:8080"
  app:
    image: your-image:latest
    deploy:
      replicas: 3
      resources:
              limits:
                cpus: "1.0"
                memory: "512M"

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"

    depends_on:
      - elasticsearch
      - fluentd

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  fluentd:
    image: fluent/fluentd:v1.14
    container_name: fluentd
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
    ports:
      - "24224:24224"
