version: '3.8'

services:
  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile for Spring Boot Application
    ports:
      - "8080:8080"
    environment:
      - PROFILE=default

  # Fibonacci Class
  fibonacci:
    build:
      context: .
      dockerfile: Dockerfile.fibonacci  # Dockerfile for Fibonacci Class
    deploy:
      resources:
        limits:
          memory: 512M

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  # Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  # Kibana Service
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # Fluentd Service
  fluentd:
    image: fluent/fluentd:v1.14
    container_name: fluentd
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
    ports:
      - "24224:24224"
